// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: remote_echo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemoteEchoService_RemoteEcho_FullMethodName = "/proto.RemoteEchoService/RemoteEcho"
)

// RemoteEchoServiceClient is the client API for RemoteEchoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoteEchoServiceClient interface {
	RemoteEcho(ctx context.Context, in *RemoteEchoRequest, opts ...grpc.CallOption) (*RemoteEchoResponse, error)
}

type remoteEchoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteEchoServiceClient(cc grpc.ClientConnInterface) RemoteEchoServiceClient {
	return &remoteEchoServiceClient{cc}
}

func (c *remoteEchoServiceClient) RemoteEcho(ctx context.Context, in *RemoteEchoRequest, opts ...grpc.CallOption) (*RemoteEchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoteEchoResponse)
	err := c.cc.Invoke(ctx, RemoteEchoService_RemoteEcho_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteEchoServiceServer is the server API for RemoteEchoService service.
// All implementations must embed UnimplementedRemoteEchoServiceServer
// for forward compatibility.
type RemoteEchoServiceServer interface {
	RemoteEcho(context.Context, *RemoteEchoRequest) (*RemoteEchoResponse, error)
	mustEmbedUnimplementedRemoteEchoServiceServer()
}

// UnimplementedRemoteEchoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemoteEchoServiceServer struct{}

func (UnimplementedRemoteEchoServiceServer) RemoteEcho(context.Context, *RemoteEchoRequest) (*RemoteEchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoteEcho not implemented")
}
func (UnimplementedRemoteEchoServiceServer) mustEmbedUnimplementedRemoteEchoServiceServer() {}
func (UnimplementedRemoteEchoServiceServer) testEmbeddedByValue()                           {}

// UnsafeRemoteEchoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteEchoServiceServer will
// result in compilation errors.
type UnsafeRemoteEchoServiceServer interface {
	mustEmbedUnimplementedRemoteEchoServiceServer()
}

func RegisterRemoteEchoServiceServer(s grpc.ServiceRegistrar, srv RemoteEchoServiceServer) {
	// If the following call pancis, it indicates UnimplementedRemoteEchoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemoteEchoService_ServiceDesc, srv)
}

func _RemoteEchoService_RemoteEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteEchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteEchoServiceServer).RemoteEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteEchoService_RemoteEcho_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteEchoServiceServer).RemoteEcho(ctx, req.(*RemoteEchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemoteEchoService_ServiceDesc is the grpc.ServiceDesc for RemoteEchoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteEchoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RemoteEchoService",
	HandlerType: (*RemoteEchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RemoteEcho",
			Handler:    _RemoteEchoService_RemoteEcho_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remote_echo.proto",
}
