// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: remote_echo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteEchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remote        string                 `protobuf:"bytes,1,opt,name=remote,proto3" json:"remote,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteEchoRequest) Reset() {
	*x = RemoteEchoRequest{}
	mi := &file_remote_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteEchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteEchoRequest) ProtoMessage() {}

func (x *RemoteEchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteEchoRequest.ProtoReflect.Descriptor instead.
func (*RemoteEchoRequest) Descriptor() ([]byte, []int) {
	return file_remote_echo_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteEchoRequest) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *RemoteEchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoteEchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteEchoResponse) Reset() {
	*x = RemoteEchoResponse{}
	mi := &file_remote_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteEchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteEchoResponse) ProtoMessage() {}

func (x *RemoteEchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteEchoResponse.ProtoReflect.Descriptor instead.
func (*RemoteEchoResponse) Descriptor() ([]byte, []int) {
	return file_remote_echo_proto_rawDescGZIP(), []int{1}
}

func (x *RemoteEchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_remote_echo_proto protoreflect.FileDescriptor

const file_remote_echo_proto_rawDesc = "" +
	"\n" +
	"\x11remote_echo.proto\x12\x05proto\"E\n" +
	"\x11RemoteEchoRequest\x12\x16\n" +
	"\x06remote\x18\x01 \x01(\tR\x06remote\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x12RemoteEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2V\n" +
	"\x11RemoteEchoService\x12A\n" +
	"\n" +
	"RemoteEcho\x12\x18.proto.RemoteEchoRequest\x1a\x19.proto.RemoteEchoResponseB3Z1github.com/teran/echo-grpc-server/presenter/protob\x06proto3"

var (
	file_remote_echo_proto_rawDescOnce sync.Once
	file_remote_echo_proto_rawDescData []byte
)

func file_remote_echo_proto_rawDescGZIP() []byte {
	file_remote_echo_proto_rawDescOnce.Do(func() {
		file_remote_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remote_echo_proto_rawDesc), len(file_remote_echo_proto_rawDesc)))
	})
	return file_remote_echo_proto_rawDescData
}

var file_remote_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_remote_echo_proto_goTypes = []any{
	(*RemoteEchoRequest)(nil),  // 0: proto.RemoteEchoRequest
	(*RemoteEchoResponse)(nil), // 1: proto.RemoteEchoResponse
}
var file_remote_echo_proto_depIdxs = []int32{
	0, // 0: proto.RemoteEchoService.RemoteEcho:input_type -> proto.RemoteEchoRequest
	1, // 1: proto.RemoteEchoService.RemoteEcho:output_type -> proto.RemoteEchoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_remote_echo_proto_init() }
func file_remote_echo_proto_init() {
	if File_remote_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remote_echo_proto_rawDesc), len(file_remote_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remote_echo_proto_goTypes,
		DependencyIndexes: file_remote_echo_proto_depIdxs,
		MessageInfos:      file_remote_echo_proto_msgTypes,
	}.Build()
	File_remote_echo_proto = out.File
	file_remote_echo_proto_goTypes = nil
	file_remote_echo_proto_depIdxs = nil
}
